### ISSUE TITLE
"Copiar elemento React" não está funcionando

### ISSUE THREAD

**Issue by souzaluiz** [solrachix/icons-manager#1]
Ao clicar com o botão direito do mouse e clicar na opção "Copiar elemento React" e depois ctrl +v é copiado um elemento ```<undefined />```
Sistema operacional Linux Zorin OS 16

**Comment by solrachix** [comment]
Uhnn... verdade, fui testar aqui e está voltando `<undefined/>` Consegue me dizer se é o mesmo retorno?

**Comment by solrachix** [comment]
> Ao clicar com o botão direito do mouse e clicar na opção "Copiar elemento React" e depois ctrl +v é copiado um elemento Sistema operacional Linux Zorin OS 16

Uhnn... verdade, fui testar aqui e está voltando `<undefined/>` Consegue me dizer se é o mesmo retorno?

**Comment by souzaluiz** [comment]
é exatamente esse retorno, esqueci das tags html aqui na issue k

**Comment by solrachix** [comment]
Vou verificar aqui e já lanço um update

**Comment by solrachix** [comment]
Já foi corrigido o bug, mas ainda vou criar uma nova release @souzaluiz

**Comment by solrachix** [comment]
@souzaluiz Atualizado a release, agora além da correção de bug, ainda acrescentei novas opções para copiar os ícones

**Comment by souzaluiz** [comment]
@solrachix perfeito, muito obrigado esse app vai ser muito útil no meu dia a dia, quero separar um tempinho para contribuir nesse projeto.

**Comment by solrachix** [comment]
Valeu @souzaluiz, toda ajuda é bem vinda 🙃
